In [1]:
from Direct_Fidelity_Estimation_gates import *

In [2]:
θ = np.random.randn(1)
ϕ = 4*np.pi/5

In [3]:
U = np.array( [ [ np.exp(-1j*ϕ/2), 0 ] , [0, np.exp(1j*ϕ/2)] ] )
V = np.array( [ [ np.cos(θ), np.sin(θ)], [np.sin(θ), -np.cos(θ)] ] )

In [4]:
U

array([[0.30901699-0.95105652j, 0.        +0.j        ],
       [0.        +0.j        , 0.30901699+0.95105652j]])

In [5]:
V

array([[[ 0.99999939],
        [ 0.00110197]],

       [[ 0.00110197],
        [-0.99999939]]])

In [6]:
abs(np.trace(U.T.conj()@V))**2/4

array([0.9045074])

In [157]:
M = 100

In [158]:
σ = np.outer( V.flatten(), V.flatten().conj() )
n = int( np.log2( σ.shape[0] ) )
paulis = np.array( [ [1,0,0,1], [0,1,1,0], [0,-1j,1j,0], [1,0,0,-1] ] ).reshape(4,2,2) / np.sqrt(2) 
Pk = n*[ paulis ]
σk = np.real( InnerProductMatrices( σ, Pk ) ).flatten()
qk = np.real( σk**2 )
Index = rm.choices( range(4**n), qk, k = M )

In [159]:
paulis

array([[[ 0.70710678+0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        ,  0.70710678+0.j        ]],

       [[ 0.        +0.j        ,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        +0.j        ]],

       [[ 0.        +0.j        , -0.        -0.70710678j],
        [ 0.        +0.70710678j,  0.        +0.j        ]],

       [[ 0.70710678+0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        , -0.70710678+0.j        ]]])

In [160]:
σ

array([[ 9.99998786e-01,  1.10196817e-03,  1.10196817e-03,
        -9.99998786e-01],
       [ 1.10196817e-03,  1.21433531e-06,  1.21433531e-06,
        -1.10196817e-03],
       [ 1.10196817e-03,  1.21433531e-06,  1.21433531e-06,
        -1.10196817e-03],
       [-9.99998786e-01, -1.10196817e-03, -1.10196817e-03,
         9.99998786e-01]])

In [161]:
ρ   = np.outer( U.flatten(), U.flatten().conj() )
ρk  = np.real( InnerProductMatrices( ρ, Pk ) ).flatten()
ρki = ρk[Index] 
ρki_exact = ρki

In [162]:
ρki

array([ 1.        ,  1.        ,  1.        ,  0.80901699,  1.        ,
       -0.80901699,  0.80901699,  1.        , -0.80901699,  1.        ,
        0.80901699, -0.80901699, -0.80901699,  0.80901699,  1.        ,
        1.        , -0.80901699, -0.80901699, -0.80901699,  0.80901699,
        1.        , -0.80901699,  1.        ,  0.80901699,  1.        ,
        0.80901699,  0.80901699, -0.80901699,  1.        , -0.80901699,
        0.80901699, -0.80901699,  1.        , -0.80901699,  1.        ,
        0.80901699,  1.        ,  1.        , -0.80901699,  1.        ,
        1.        ,  0.80901699, -0.80901699,  0.80901699,  0.80901699,
        1.        , -0.80901699, -0.80901699,  0.80901699,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        0.80901699,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  0.80901699,  1.        , -0.80901699,  1.        ,
        1.        ,  0.80901699,  0.80901699,  1.        ,  1.  

In [163]:
ρ

array([[ 1.        +0.j        ,  0.        -0.j        ,
         0.        -0.j        , -0.80901699-0.58778525j],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [-0.80901699+0.58778525j,  0.        +0.j        ,
         0.        +0.j        ,  1.        +0.j        ]])

In [164]:
σki = σk[Index] 
Fid = np.real( np.sum( ρki/σki )/M ) 
Fid

0.9025997655105001

In [165]:
circ_U = QuantumCircuit(1)
circ_U.rz(ϕ,0)

In [166]:
Index_b4 = [ convert_to_base( index, 4, n) for index in Index]
Labels = Index_b4
Labels

['33',
 '33',
 '33',
 '22',
 '33',
 '11',
 '22',
 '00',
 '11',
 '33',
 '22',
 '11',
 '11',
 '22',
 '33',
 '00',
 '11',
 '11',
 '11',
 '22',
 '33',
 '11',
 '33',
 '22',
 '00',
 '22',
 '22',
 '11',
 '00',
 '11',
 '22',
 '11',
 '33',
 '11',
 '00',
 '22',
 '33',
 '00',
 '11',
 '00',
 '33',
 '22',
 '11',
 '22',
 '22',
 '33',
 '11',
 '11',
 '22',
 '00',
 '00',
 '00',
 '00',
 '33',
 '00',
 '22',
 '33',
 '00',
 '00',
 '00',
 '33',
 '22',
 '00',
 '11',
 '33',
 '00',
 '22',
 '22',
 '00',
 '00',
 '11',
 '22',
 '11',
 '00',
 '00',
 '11',
 '11',
 '11',
 '33',
 '00',
 '22',
 '00',
 '11',
 '33',
 '11',
 '22',
 '33',
 '33',
 '11',
 '33',
 '33',
 '22',
 '22',
 '22',
 '33',
 '33',
 '22',
 '33',
 '22',
 '00']

In [167]:
quantum_instance = QuantumInstance( Aer.get_backend('aer_simulator'), shots=2**13 )

In [179]:
n = circ_U.num_qubits
M = len(Labels)

if not isinstance(Labels, list):
    Labels = [Labels]

EigenValues = [
            np.array([ 1.,  1. ]),
            np.array([ 1., -1. ]),
            np.array([ 1., -1. ]),
            np.array([ 1., -1. ])
            ] 

Circuits = []
Labels_out = []
ExpectedValues = M*[None]
Indx = []

for m in range(M):
    label = Labels[m]
    if label == ''.zfill(2*n):
        ExpectedValues[m] = 1  
    else:
        Indx.append(m)
        Labels_out.append(label)
        circuit_0 = QuantumCircuit(n,n)
        circuit_1 = QuantumCircuit(n,n)
        
        if label[1] == '0' or label[1] == '3' :
            circuit_0.barrier()
            circuit_1.x(0)
            circuit_1.barrier()
            
        elif label[1] == '1':
            circuit_0.h(0)
            circuit_0.barrier()
            circuit_1.x(0)
            circuit_1.h(0)
            circuit_1.barrier()
            
        elif label[1] == '2' : 
            circuit_0.x(0)
            circuit_0.u2(np.pi/2,np.pi,0) 
            circuit_0.barrier()
            circuit_1.u2(np.pi/2,np.pi,0) 
            circuit_1.barrier()
            
        circuit_0.compose( circ_U, qubits=range(n), inplace=True) 
        circuit_0.barrier()
        circuit_1.compose( circ_U, qubits=range(n), inplace=True) 
        circuit_1.barrier()
        
        if label[0] == '1':
            circuit_0.h(0)
            circuit_1.h(0)
        elif label[0] == '2' :
            circuit_0.u2(0,np.pi/2,0) 
            circuit_1.u2(0,np.pi/2,0) 
            
        circuit_0.measure(range(n),range(n))
        circuit_1.measure(range(n),range(n))
        
        Circuits.append( circuit_0 )       
        Circuits.append( circuit_1 )       
        

In [180]:
Circuits[0].draw()

░ ┌──────────┐ ░ ┌─┐
q_0: ─░─┤ Rz(4π/5) ├─░─┤M├
      ░ └──────────┘ ░ └╥┘
c: 1/═══════════════════╩═
                        0

In [181]:
len(Circuits)

152

In [182]:
Job = quantum_instance.execute( Circuits )
probs = get_probabilities( Job )

In [183]:
probs

array([[1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 0.90307617, 0.09851074, 1.        , 0.        ,
        0.09228516, 0.90759277, 0.90185547, 0.09619141, 0.09973145,
        0.90881348, 1.        , 0.        , 0.90283203, 0.09655762,
        0.09277344, 0.90209961, 0.09509277, 0.90246582, 0.90332031,
        0.09143066, 1.        , 0.        , 0.09204102, 0.90185547,
        0.09143066, 0.90100098, 0.09985352, 0.90368652, 0.90686035,
        0.10009766, 1.        , 0.        , 0.09509277, 0.90148926,
        1.        , 0.        , 0.90441895, 0.10229492, 0.9029541 ,
        0.1003418 , 0.90649414, 0.09265137, 0.10632324, 0.90161133,
        0.09399414, 0.90637207, 0.91027832, 0.09020996, 0.09313965,
        0.90808105, 1.        , 0.        , 0.10058594, 0.91137695,
        0.90612793, 0.09716797, 1.        , 0.        , 0.09484863,
        0.90527344, 1.        , 0.        , 0.90612793, 0.09814453,
        0.09777832, 0.91247559, 0.90100098, 0.09

In [184]:
probs.T

array([[1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.90307617, 0.09692383],
       [0.09851074, 0.90148926],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.09228516, 0.90771484],
       [0.90759277, 0.09240723],
       [0.90185547, 0.09814453],
       [0.09619141, 0.90380859],
       [0.09973145, 0.90026855],
       [0.90881348, 0.09118652],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.90283203, 0.09716797],
       [0.09655762, 0.90344238],
       [0.09277344, 0.90722656],
       [0.90209961, 0.09790039],
       [0.09509277, 0.90490723],
       [0.90246582, 0.09753418],
       [0.90332031, 0.09667969],
       [0.09143066, 0.90856934],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.09204102, 0.90795898],
       [0.90185547, 0.09814453],
       [0.

In [185]:
Labels_out

['33',
 '33',
 '33',
 '22',
 '33',
 '11',
 '22',
 '11',
 '33',
 '22',
 '11',
 '11',
 '22',
 '33',
 '11',
 '11',
 '11',
 '22',
 '33',
 '11',
 '33',
 '22',
 '22',
 '22',
 '11',
 '11',
 '22',
 '11',
 '33',
 '11',
 '22',
 '33',
 '11',
 '33',
 '22',
 '11',
 '22',
 '22',
 '33',
 '11',
 '11',
 '22',
 '33',
 '22',
 '33',
 '33',
 '22',
 '11',
 '33',
 '22',
 '22',
 '11',
 '22',
 '11',
 '11',
 '11',
 '11',
 '33',
 '22',
 '11',
 '33',
 '11',
 '22',
 '33',
 '33',
 '11',
 '33',
 '33',
 '22',
 '22',
 '22',
 '33',
 '33',
 '22',
 '33',
 '22']

In [186]:
for k in range(len(Labels_out)):
    if Labels_out[k][0] == '0':
        S0 = probs[1,2*k] + probs[0,2*k]
        S1 = probs[1,2*k+1] + probs[0,2*k+1]
    else:
        S0 = - probs[1,2*k] + probs[0,2*k]
        S1 = - probs[1,2*k+1] + probs[0,2*k+1]
        
    print(S0, S1)
    if Labels_out[k][1] == '0':
        ExpectedValues[ Indx[k]] = S1/2. + S0/2.
    else:
        ExpectedValues[ Indx[k]] = -S1/2. + S0/2.


1.0 -1.0
1.0 -1.0
1.0 -1.0
0.80615234375 -0.802978515625
1.0 -1.0
-0.8154296875 0.815185546875
0.8037109375 -0.8076171875
-0.800537109375 0.817626953125
1.0 -1.0
0.8056640625 -0.806884765625
-0.814453125 0.80419921875
-0.809814453125 0.804931640625
0.806640625 -0.817138671875
1.0 -1.0
-0.81591796875 0.8037109375
-0.817138671875 0.802001953125
-0.80029296875 0.807373046875
0.813720703125 -0.7998046875
1.0 -1.0
-0.809814453125 0.802978515625
1.0 -1.0
0.808837890625 -0.79541015625
0.805908203125 -0.79931640625
0.81298828125 -0.814697265625
-0.787353515625 0.80322265625
-0.81201171875 0.812744140625
0.820556640625 -0.819580078125
-0.813720703125 0.816162109375
1.0 -1.0
-0.798828125 0.82275390625
0.812255859375 -0.8056640625
1.0 -1.0
-0.810302734375 0.810546875
1.0 -1.0
0.812255859375 -0.8037109375
-0.804443359375 0.824951171875
0.802001953125 -0.81005859375
0.81298828125 -0.8134765625
1.0 -1.0
-0.812744140625 0.812255859375
-0.813720703125 0.8134765625
0.79736328125 -0.806396484375
1.0 -1.

In [187]:
np.array( [ ExpectedValues, ρki_exact , Labels]).T

array([['1.0', '0.9999999999999997', '33'],
       ['1.0', '0.9999999999999997', '33'],
       ['1.0', '0.9999999999999997', '33'],
       ['0.8045654296875', '0.8090169943749471', '22'],
       ['1.0', '0.9999999999999997', '33'],
       ['-0.8153076171875', '-0.8090169943749471', '11'],
       ['0.8056640625', '0.8090169943749471', '22'],
       ['1', '0.9999999999999997', '00'],
       ['-0.80908203125', '-0.8090169943749471', '11'],
       ['1.0', '0.9999999999999997', '33'],
       ['0.8062744140625', '0.8090169943749471', '22'],
       ['-0.809326171875', '-0.8090169943749471', '11'],
       ['-0.807373046875', '-0.8090169943749471', '11'],
       ['0.8118896484375', '0.8090169943749471', '22'],
       ['1.0', '0.9999999999999997', '33'],
       ['1', '0.9999999999999997', '00'],
       ['-0.809814453125', '-0.8090169943749471', '11'],
       ['-0.8095703125', '-0.8090169943749471', '11'],
       ['-0.8038330078125', '-0.8090169943749471', '11'],
       ['0.8067626953125', '0.809

In [192]:
np.mean( np.sum( np.array( [ ExpectedValues, -ρki_exact ] ), 0) )

-0.000309408224999308